# -*- coding: utf-8 -*-
"""scrap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j3BrEtd2PkmUGrETlLXPKXFdX4JkXUL6
"""

import pandas as pd
import requests
from bs4 import BeautifulSoup
from io import StringIO

url = "https://en.wikipedia.org/wiki/List_of_largest_companies_by_revenue"
headers = {"User-Agent": "MyProject/1.0 (binii@example.com)"}

page = requests.get(url, headers=headers)
soup = BeautifulSoup(page.text, 'html.parser')

tables = pd.read_html(StringIO(str(soup)))
print(len(tables))  # see how many tables found
df = tables[0]

df.to_csv("largest_company.csv", index=False)
print("saved!")

import os
os.getcwd()  # shows you where it saved

from google.colab import files
files.download("largest_company.csv")

df=pd.read_csv("largest_company.csv")
df.head()

df = df.iloc[1:].reset_index(drop=True)  # clean
df.to_csv("largest_companies.csv", index=False)  # overwrite the old csv
print("saved!")

df.head()